### ISSUE TITLE
6. Arrays

### ISSUE THREAD

**Issue by ReneKrewinkel** [BennoBalter/educom-javascript-basis#6]
<p>Bestudeer de module:</p>
<ul>
<li><a href="https://e-learning.educom.nu/essentials/JS/arrays">https://e-learning.educom.nu/essentials/JS/arrays</a></li>
<li>maak de opdracht</li>
</ul>

**Comment by BennoBalter** [comment]
Wat speciaals gebeurt er bij modify?

**Comment by BennoBalter** [comment]
Waarom hoeft deze functie niet geloopt te worden? 
const points2 = [40, 100, 1, 5, 25, 10]
    points2.sort( (a,b) => a - b )
    console.log({ proper: points2 }
